#!/bin/sh
url="https://en.wikipedia.org/w/index.php?title=$(urlencode "$*")"

exec lynx "$url"
# w3m "$url"
# exec lynx "en.wikipedia.org/w/index.php?title=$*"
# w3m "en.wikipedia.org/w/index.php?title=$*"
